# Generated by Django 3.0.14 on 2021-10-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='ordinality',
            field=models.IntegerField(unique=True),
        ),
    ]
